### ISSUE TITLE
Multiple phone open with the application, application cant see all phone 

### ISSUE THREAD

**Issue by magenapp** [MohGovIL/rn-contact-tracing#21]
work with 6 phones 
Samsung S9+,Samsung 6Ege,Samsung 6, LG G7,LG G6, LG G4
All identify by all using device BT 
open the application on all devices 
Scan - interval 55000, Duration 5000
Advertise - interval 50000, Duration 10000
not all phobe visible to all in the application result
LG4 - scan results - samsung6,samsung 9 and LG7
LG6 - scan results - samsung 6, LGG7,LGG4 and samsung S9
LG G7- scan results - samsung 6, LGG4 and Samsung S9
Samsung Galaxy 9+ - samsung 6, LGG4,LGG7
Samsung 6 - LGG4,Samsung S9, and LGG7
Samsung S6edge - samsung 6'LG G4'Samsung s9and LG G7

!
![IMG_0012](https://user-images.githubusercontent.com/62991324/80111684-db544180-8588-11ea-9de5-9ad6a6d60d61.JPG)

**Comment by jabzum** [comment]
Did you find any solution?

**Comment by kaplanlior** [comment]
Hi @jabzum , this components works on the BLE part and cross referencing authenticated patient  that come through the app at @MohGovIL/hamagen-react-native .

**Comment by jabzum** [comment]
So if I wanted to make my own app to detect infected and all the flow of a contact tracing, is this plugin not the option I'm looking for? :(

**Comment by kaplanlior** [comment]
This plugin is the infrastructure for such an app. It will log the contacts you had over time. But you'll need MOH to let you know which people (technically - which hashes) are of authenticated patients.
